### PR TITLE
filter-button

### LINKED ISSUE #580: bug: Filters are not working
Screenshot 2024-08-27 at 11 41 32 AM

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
### PR Fixes:
- Filter button Bug (UI)

Resolves #580

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
@hkirat , the filter button doesnt work because the cohort value in the db is zero
Screenshot 2024-08-27 at 12 18 30 PM

**Comment by ItsFlash10** [comment]
> @hkirat , the filter button doesnt work because the cohort value in the db is zero
> 
> Screenshot 2024-08-27 at 12 18 30 PM

That's not the case in prod as cohort is set to 3 and by default every new track added is set to cohort:3
Also your change just toggle the button but I guess the issue was for data not be populated with the filters

**Comment by Ashutoshpadhi629** [comment]
> > @hkirat , the filter button doesnt work because the cohort value in the db is zero
> > Screenshot 2024-08-27 at 12 18 30 PM
> 
> That's not the case in prod as cohort is set to 3 and by default. For every new track added, value is cohort:3. Also your change just toggle the button but I guess the issue was for data not be populated with the filters

changing the values in db makes it work , also the button logic was not correct as , clicking on cohort 3 button does not set the cohort 2 button false .

https://github.com/user-attachments/assets/59203035-602f-45d8-a87f-c22a064df9d3

**Comment by ItsFlash10** [comment]
> @ItsFlash10 , changing the values in db makes it work , also the button logic was not correct as , clicking on cohort 3 button does not set the cohort 2 button false .
> 
>  Screen.Recording.2024-08-27.at.12.37.02.PM.mov

Yes that's what, the issue you solved is correct but a different issue from what he mentioned is what I meant xD.

**Comment by Ashutoshpadhi629** [comment]
@ItsFlash10 , you were right, makes sense now , Thanks.

**Pull request closed without merging**
