### PR TITLE
Workflow/restrict lock files other than yarn

### LINKED ISSUE #243: Create an action that fails if the user has committed package-lock
Users are committing package-lock and `pnpm-lock`
We're restricting the repo to yarn, so any PR that adds either of these should be rejected

Let's add a workflow that checks this

### PR DESCRIPTION
**Pull request by Rahul-Das-Sarma**
### PR Fixes:
- 1 1 Added Pre Script to check lock files such as pnpm.lock, bun.lockb ,package.lock to be restricted from committing.

Resolves #243

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

https://github.com/code100x/daily-code/assets/63789293/4a54447c-944b-41d7-9535-c0802e376589

### CODE REVIEW

**Comment by hkirat** [comment]
Any reason u got rid of yarn lock?

**Comment by Rahul-Das-Sarma** [comment]
It was showing merge conflicts. As yarn.lock file automatically gets generated during installation. Hence, decided to delete it.

**Comment by devsargam** [comment]
> automatically gets generated during installation

No, yarn need context of what version of packages are the packages inside ur package.json depend upon. Very risky thing to do

**Comment by Rahul-Das-Sarma** [comment]
I apologise, so if it's okay may I re-add it and push the code?

**Comment by devsargam** [comment]
Can u go back a commit and push the code?
doing
```
yarn install
```
wont help

**Comment by Rahul-Das-Sarma** [comment]
Sure, I am doing it

**Comment by Rahul-Das-Sarma** [comment]
Hi, I have reverted the deletion. Please let me know if I need to do anything further. Thank you.

**Comment by hkirat** [comment]
Just copy over yarn lock from master and replace in this branch

**Comment by Rahul-Das-Sarma** [comment]
Adding it

**Comment by Rahul-Das-Sarma** [comment]
I have made the changes. I was thinking of adding commitlint as well to enforce standardized commit. Please let me know, if i should work on it

**Comment by SujithThirumalaisamy** [comment]
> I have made the changes. I was thinking of adding commitlint as well to enforce standardized commit. Please let me know, if i should work on it

Ahh... I think vs code is being vs code and thows lint issues very often. This will be twisting heads there?

**Comment by devsargam** [comment]
@SujithThirumalaisamy the lint issues is due to prettier eslint conflicts

**Comment by Rahul-Das-Sarma** [comment]
I don't know about😁.. that but this can definitely help contributors learn about commit lint  and write proper commit messages. But it is definitely not mandatory thing

**Pull request merged**
