### PR TITLE
feat(#576)/added search on frontend with fuse.js

### LINKED ISSUE #576: feature: add a search on the frontend
**Is your feature request related to a problem? Please describe.**
Currently, the search functionality is not working properly since the API key for search has expired.

**Describe the solution you'd like**
Just search the title of all the topics we are getting from the backend. Use [Fuse.js](https://www.fusejs.io/) to do some fuzzy search.

**Additional context**
Don't remove the elastic search logic just replace with fusejs as an interim solution

### PR DESCRIPTION
**Pull request by toufiqfarhan0**
### PR Fixes:
-  Added a Search on front-end.
- Search the title of all the topics we are getting from the backend.
- Used Fuse.js library for fuzzy search.
- Added Speech to the Search bar.

Resolves #576 

https://github.com/user-attachments/assets/a04dff5e-3493-4381-8285-6e816654cc74

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by toufiqfarhan0** [comment]
@hkirat @devsargam can you please review it??

**Comment by devsargam** [comment]
@toufiqfarhan0 later tonight

**Comment by toufiqfarhan0** [comment]
> @toufiqfarhan0 later tonight

Done.

**Review by rushhaaland — COMMENTED** [review]
why the linting checks are getting failed ?

**Comment by toufiqfarhan0** [comment]
> why the linting checks are getting failed ?

this thing hasn't changed in main repo

image

**Comment by devsargam** [comment]
Closing in favour of https://github.com/code100x/daily-code/pull/578

**Pull request closed without merging**
