### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vivek-1102**

### CODE REVIEW

**Comment by SujithThirumalaisamy** [comment]
Feel free to add the Actionable docker for postgres too. So we can push this in a single commit

**Comment by Vivek-1102** [comment]
hey i really dont know about the docker command for postgres can you help me getting this?

**Comment by Vivek-1102** [comment]
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres
is this command good ?

**Comment by SujithThirumalaisamy** [comment]
# Actionable docker Postgres setup
```
docker run --name <your-db-name> -p 5432:5432 -e POSTGRES_PASSWORD=<your-db-password> -d postgres
```
Change```<your-db-name>``` and ```<your-db-password>``` with a ```Database Name``` and ```Database Password```
>Sample DATABASE_URL
```
postgresql://postgres:<your-db-pass>@localhost:5432/postgres?schema=public
```

**Comment by Vivek-1102** [comment]
I have made a new pull request with the required chances plz check it

**Pull request closed without merging**
