### PR TITLE
fix filter bug

### LINKED ISSUE #580: bug: Filters are not working
Screenshot 2024-08-27 at 11 41 32 AM

### PR DESCRIPTION
**Pull request by DeepanshuMishraa**
### PR Fixes:
- 1 Fixed the Filter not working bug

Resolves #580 

The main cause for the issue was the default value of the cohort being 0 in the tracks table which was considering the cohort value to be zero which doesn't exist 

Preview of the fix:
image
image

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by DeepanshuMishraa** [comment]
Hey @hkirat @devsargam,
This PR addresses two key issues:

Fixed the cohort button logic - now only one cohort (2 or 3) can be selected at a time.
Resolved the filtering issue caused by the default cohort value of 0 in the tracks table.

Let me know if you'd like any tweaks  or if there's any issue!

**Comment by ItsFlash10** [comment]
This caters for a different issue related to the button toggle but please check [this](https://github.com/code100x/daily-code/issues/580#issuecomment-2311753073) once, I hope it make sense and is what @hkirat was referring to.

**Comment by nischal-shetty2** [comment]
Hey @DeepanshuMishraa able the run locally after the recent commit?
im getting this error after pulling the recent commits(was working fine last i checked 2 days back)
Screenshot 2024-08-27 at 2 36 29 PM
saw the logs in docker desktop and it breaks while seeding probably
Screenshot 2024-08-27 at 2 37 33 PM
@devsargam could you help please, should i raise an issue for this?

**Comment by DeepanshuMishraa** [comment]
> Hey @DeepanshuMishraa able the run locally after the recent commit?
> im getting this error after pulling the recent commits(was working fine last i checked 2 days back)
> Screenshot 2024-08-27 at 2 36 29 PM
> saw the logs in docker desktop and it breaks while seeding probably
> Screenshot 2024-08-27 at 2 37 33 PM
> @devsargam could you help please, should i raise an issue for this?

Yeah I was facing the same, I guess something is wrong with dockerfile 

Just start a postgres db locally and replace the db string in .env

**Comment by devsargam** [comment]
Hi guys, can u start the project mannually

**Comment by devsargam** [comment]
Seems like this wasn't a bug. Closing for now. Reopen if you think it is

**Pull request closed without merging**
