### PR TITLE
ui changes

### LINKED ISSUE #527: feature: The prev and next button should be at the bottom of the page
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by keshav-exe**
### PR Fixes:
- 1 UI Upgrade
- 2 Fixed Categorisation & Added "Cohort 2.0" & "Cohort 3.0"

Resolves #527 #530 #531 #535 #540 #549 #552 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

Screenshot

### CODE REVIEW

**Comment by devsargam** [comment]
LGTM, merging this after all other PR's are merged.

**Comment by keshav-exe** [comment]
cool, thanks!

**Comment by nischal-shetty2** [comment]
@keshav-exe could you share more screenshots on all the changes that you made, want to avoid making any changes involving them. btw ui looks sick

**Comment by keshav-exe** [comment]
fixed the notion renderer in the latest commit

localhost_3000_tracks_w5E6PT2t0IyOFM3bZxcM_aws-fe-4
localhost_3000_auth_callbackUrl=http2F3A3000%2F

**Comment by ItsFlash10** [comment]
@devsargam @hkirat please check this for Notion Renderer redesign: #555

**Comment by keshav-exe** [comment]
@devsargam fixed the issues we discussed.

**Comment by devsargam** [comment]
Your design looks great sir. Only problem that I can see is getting this error when clicking the download button

image

**Comment by keshav-exe** [comment]
looking into it

**Comment by keshav-exe** [comment]
@devsargam fixed it please take a look

**Comment by hkirat** [comment]
This got a lot of merge conflicts
Tryingt o fix locally

**Comment by ItsFlash10** [comment]
> This got a lot of merge conflicts Tryingt o fix locally

I have resolved the conflicts in my PR maybe you can have a look #555

**Comment by ItsFlash10** [comment]
> > This got a lot of merge conflicts Tryingt o fix locally
> 
> I have resolved the conflicts in my PR maybe you can have a look #555

Just saw you closed it, actually there were only 7odd file changes in my PR for Notion renderer changes but since #532 wasn't merge and I needed the new design I cut the branch from @keshav-exe's `ui-redesign` branch so those files are there in the diff too :)

**Comment by hkirat** [comment]
Moved changes to https://github.com/code100x/daily-code/pull/572/ , resolved conflicts there

**Pull request closed without merging**
