### PR TITLE
feature: #573: Added track in the sidebar and improved theme for NotionRender

### LINKED ISSUE #573: feature: Sidebar should show the various stages on the left
Screenshot 2024-08-26 at 10 15 08 PM

### PR DESCRIPTION
**Pull request by ItsFlash10**
### PR Fixes: 
- Added tracks in the sidebar.
- Fixed package dependencies due to which build was failing
- Changed next.config.js to app image domain 
- Changed NotionRender to new improved theme

Resolves #573 

### Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I assure there is no similar/duplicate pull request regarding same issue

Screenshot 2024-08-27 at 12 32 55 AM
Screenshot 2024-08-27 at 12 33 05 AM

### CODE REVIEW

**Comment by ItsFlash10** [comment]
Added yarn.lock as I have added a couple of dependencies which were missing in the `main` branch, particularly `framer-motion` and `date-fns`. Lemme know if its fine or do I need to revert that file change.
@devsargam @hkirat

**Comment by devsargam** [comment]
Testing this locally

**Review by devsargam — APPROVED** [review]

**Comment by devsargam** [comment]
Thank you sir. UI looks very clean

**Comment by ItsFlash10** [comment]
Thanks :)

**Comment by ItsFlash10** [comment]
@hkirat check here for:  #579  #584

**Pull request merged**
