### PR TITLE
feat: Added Keyboard Navigation and selection in SearchDialog component

### PR DESCRIPTION
**Pull request by ssk090**
# Pull Request Summary
- Enhancements to SearchDialog for Keyboard Navigation
- The modifications allow users to navigate through search results using the up and down arrow keys and to select a search result using the Enter key.

https://github.com/code100x/daily-code/assets/22127725/bead361d-d35d-4cf9-abdc-c3a09608cd2e

### CODE REVIEW

**Comment by ssk090** [comment]
hey @hkirat, please check this PR.
It incorporates keyboard navigation functionality into the search bar, enhancing accessibility for users who prefer a mouse-free browsing experience.

Thank you

**Comment by hkirat** [comment]
Feel like someoone else did it already

**Comment by ssk090** [comment]
> Feel like someoone else did it already

I wanted to have the mouse-free experience, so i raised the PR. Will wait for the next update. Thanks.

**Comment by ruhankhandakar** [comment]
> Feel like someoone else did it already

https://github.com/code100x/daily-code/pull/77 
1 month ago I raised this PR @hkirat :(

**Pull request merged**
