### PR TITLE
Fixed: Admin

### LINKED ISSUE #142: feat/Add Admin Dashboard with complete control
# Add Admin Dashboard with ability to add tracks, edit tracks, create MCQ questions, create code questions 

- Tracks should be added directly from the dashboard with ability to revalidate ssg cache for each track.
- MCQ questions can be added for each track directly through the dashboard
- Code problems (as #112 )

Would like to work on this - since people are working on DSA problems and mcq already - could only work on creating tracks and revalidating cache.

### LINKED ISSUE #176: [urgent] Let admins put a notion doc top level page that auto creates a track
Right now , the process of creating a track looks like this - 

1. Educator creates the track (Ref - https://www.notion.so/Redis-Pub-subs-and-Messaging-queues-2954d8a8a782433e8775dc179dff3033 )
2. Mods manually seed data in the database

Would be nice if somehow all titles and pages are autoscraped so the admin can simply add the top level page (https://www.notion.so/Redis-Pub-subs-and-Messaging-queues-2954d8a8a782433e8775dc179dff3033 ) and the title, image and the page is created automatically

So the `problems` in the DB need to be scraped from the top level notion page

### PR DESCRIPTION
**Pull request by ShubhamMewara**
Fixed #142 also,
Fixed #176 
Added feat to add and edit Problems and Tracks in admin

Final Changes

https://github.com/code100x/daily-code/assets/136337515/98628979-38de-462d-bec2-ccc042a891a2

### CODE REVIEW

**Comment by ShubhamMewara** [comment]
[Added feat to link Track and Problems](https://github.com/code100x/daily-code/pull/152/commits/cae2948e5aefa2298bea835d20f17918ef31801e)


https://github.com/code100x/daily-code/assets/136337515/909b0819-cb9a-424c-80aa-770af1985d1d

**Comment by hkirat** [comment]
good start
its missing
1. image in the track
2. A way to attach problems to tracks

LMK if u'd like to work on it. If not we can merge this as is and someone else can pick it up

**Comment by hkirat** [comment]
What does `LinkProblems` do?

**Comment by ShubhamMewara** [comment]
> [Added feat to link Track and Problems](https://github.com/code100x/daily-code/pull/152/commits/cae2948e5aefa2298bea835d20f17918ef31801e)

> What does `LinkProblems` do?

it lets users add existing Problems to a track by using ProblemID.
I have attached video of it 
>  link.mp4

**Comment by ShubhamMewara** [comment]
> good start its missing
> 
> 1. image in the track
> 2. A way to attach problems to tracks
> 
> LMK if u'd like to work on it. If not we can merge this as is and someone else can pick it up

**Comment by ShubhamMewara** [comment]
> 1. image in the track

it shows the image link for now do you want it to image
and image link when click on edit

**Comment by ShubhamMewara** [comment]
> LMK if u'd like to work on it. If not we can merge this as is and someone else can pick it up

I would like to work on it and #176

**Comment by ShubhamMewara** [comment]
hey @hkirat ,
I have Added auth to Admin and
> 

> good start its missing
> 
> 1. image in the track

Changed the image link text to 'Image'. 
Now, I will work on #176. You can merge it, or I can commit to this PR only, whichever you prefer.

https://github.com/code100x/daily-code/assets/136337515/f0bafb0f-ca54-4da4-9849-8fa0d0f1889b

**Comment by ShubhamMewara** [comment]
@hkirat 
Added #176 

https://github.com/code100x/daily-code/assets/136337515/1787577a-703b-480b-8ed4-281a7a2e1b04

**Comment by hkirat** [comment]
reviewing

**Comment by hkirat** [comment]
Didnt review it too much will be merging and winging it
If there are follow ups will create and more issues and tag you @ShubhamMewara 
/bounty $125

**Comment by nimit9** [comment]
Can't we add a role in the authOptions callback, 
Verify the role from `.env` file

Similar to how it's done in cms

And in /app/admin, add a layout.tsx file which will check the if the role is admin, otherwise redirect to "/"

@hkirat @ShubhamMewara

**Comment by ShubhamMewara** [comment]
@nimit9 can you tell why that is a better option?

**Comment by nimit9** [comment]
Will have to manually add the admin boolean to the db.

**Comment by ShubhamMewara** [comment]
ok, I will do it if @hkirat asked thank you.

**Comment by ShubhamMewara** [comment]
> Didnt review it too much will be merging and winging it If there are follow ups will create and more issues and tag you @ShubhamMewara /bounty $125

Ok , Thank you

**Comment by nimit9** [comment]
Determining admin role can be done anyhow, but adding the check in layout.tsx makes more sense.

This way, there will be a central check done for admin.

Anyone can add the feature in /admin without worrying about how to protect it.

**Comment by hkirat** [comment]
Ah that probably makes sense why it was done re: local development
Personally I like it better for it to be in the DB
For this repo this is fine

**Comment by hkirat** [comment]
Also I'm going through the change and it is very comprehensive. 
Amazing job @ShubhamMewara

**Comment by ShubhamMewara** [comment]
@hkirat 
Thank you so much!

**Comment by nimit9** [comment]
Yes, good job @ShubhamMewara.

**Comment by ShubhamMewara** [comment]
> Yes, good job @ShubhamMewara.
Thank you.

**Pull request merged**
