### PR TITLE
feature added

### LINKED ISSUE #549: feature: Create custo renderer for everything that comes from notion
Add custom renderers for
1. headings, 
2. text blocks
So they look slightly prettier than what it looks like right now
Screenshot 2024-08-20 at 12 08 52 PM

### PR DESCRIPTION
**Pull request by AshrithSathu**
### PR Fixes:
- 1 ) custom renderers for headings, text blocks (primarily CSS)

Resolves #549

### Checklist before requesting a review
- [ ☑️] I have performed a self-review of my code
- [ ☑️] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by AshrithSathu** [comment]
can be merged please check @hkirat

**Comment by SujithThirumalaisamy** [comment]
Can you please add some screenshots?

**Comment by hkirat** [comment]
Always post screenshots if u are making a ui change
closing for now

**Comment by AshrithSathu** [comment]
> Always post screenshots if u are making a ui change closing for now

sure Harkirat thanks!

**Pull request closed without merging**
