### PR TITLE
Notion Renderer's Redesign and its code refactoring

### LINKED ISSUE #549: feature: Create custo renderer for everything that comes from notion
Add custom renderers for
1. headings, 
2. text blocks
So they look slightly prettier than what it looks like right now
Screenshot 2024-08-20 at 12 08 52 PM

### PR DESCRIPTION
**Pull request by ItsFlash10**
### PR Fixes:
- Changed the theme of NotionRenderer in compliance with the app theme.
- Refactored the code and made it cleaner for CodeBlock.
- Fixed the copy button and added a copied message upon clicking on it.
- **Contains  #532  changes made by @keshav-exe** [Opened this PR considering his contribution will remain intact which @hkirat also mentioned in his video yesterday]

Resolves #549  

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue => There's a similar PR since @keshav-exe did similar changes to what I did yesterday so opening the PR for @devsargam to decide :) 

https://github.com/user-attachments/assets/f347b187-1abc-4453-a94d-8e0a122238a6

Screenshot 2024-08-21 at 3 25 52 AM (2)
Screenshot 2024-08-21 at 3 26 03 AM (2)

### CODE REVIEW

**Comment by keshav-exe** [comment]
Looks great buddy! 🙌🏼

**Comment by ItsFlash10** [comment]
Resolved merge conflict

**Comment by hkirat** [comment]
Why is there so much noise in this PR?
Please remvoe all the lint changes before PRing

**Comment by hkirat** [comment]
closing for now, pelase reopen with lesser noise

**Comment by ItsFlash10** [comment]
> Why is there so much noise in this PR? Please remvoe all the lint changes before PRing

The branch was created from #532 so the diff is more with all those changes but I changed only like 7odd files for #549.
Will raise a PR once  #532 is merged :)

**Pull request closed without merging**
