### PR TITLE
track history added

### LINKED ISSUE #434: feature: Track history
The Track History feature records the last visited page of a track for each user, enabling users to resume their progress from where they left off.

We can store the last visited page so that can be used to navigate the user.

We can also use that to track and analyze the progress of user and in future can send marketing reminders.

### PR DESCRIPTION
**Pull request by yash-kh**
### PR Fixes:
- 1 User can start where they left off 
- 2 We also have an "isCompleted" field which tracks the track, and we can further use it to analyze and marketing reminders.

https://github.com/code100x/daily-code/assets/60394241/1ad95c1a-d68c-4627-a447-5408682c8811

Resolves #434

### CODE REVIEW

**Comment by yash-kh** [comment]
@hkirat Check out this feature!

**Comment by yash-kh** [comment]
@hkirat Incorporated track preview feature with track history

Bug fix:
- No key for map in Track Preview.

**Comment by yash-kh** [comment]
https://github.com/code100x/daily-code/assets/60394241/dc24177d-c05d-49b1-9f62-aa2485168622

**Comment by hkirat** [comment]
I think this'll just complicate things
I like the feature and implementation, unsure if this is needed
Will think a bit about it

**Comment by iamnithishraja** [comment]
@hkirat if you merge this ill add recommendation system.

**Pull request closed without merging**
