### PR TITLE
setupDB shell bug fix

### LINKED ISSUE #406: bug: setupDB shell bug
When we use this script, it throws a unique constraint error as we are running the seed twice.

1. Drop the DB
2. Rerun the setupDB script using:
- cd packages/db
- chmod +x ./setupDB.sh
- ./setupDB.sh

It should not run twice.
Screenshot 2024-05-11 at 1 00 35 PM

### PR DESCRIPTION
**Pull request by yash-kh**
### PR Fixes:
-  setupDB.sh shell bug fix 
    Initially, when we use this script, it throws a unique constraint error as we are running the seed twice. Fixed that by checking if it already ran by the output.

Resolves #406

### CODE REVIEW

**Comment by yash-kh** [comment]
Addition bug fix:
1. wrong statement changed from 'Enter your db password' to 'Enter your db username'

Additional feature:
1. lower case are accepted now for the DB script

**Comment by hkirat** [comment]
sorry there seem to be some conflicts here

**Comment by yash-kh** [comment]
@hkirat Hey merged main and resolved conflicts.

**Pull request merged**
