### PR TITLE
feat-602: Added leagacy mode button on Blog Page

### LINKED ISSUE #602: feature: add a legacy mode button to daily-code
### There should be a toggle button which toggles between the new fancy ui and old legacy one

image

image

### PR DESCRIPTION
**Pull request by ItsFlash10**
### PR Fixes:
- Added a legacy mode button to toggle between the new and the old UI on the Blog page.
- Fixed and improved the legacy UI a lil which was required (eg. header)
- Improved Mobile and Tablet view.
- Added pretier-tailwind for sorting the tailwind classes better.

Resolves #602  

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

@devsargam @hkirat 

iPad Air 4 - localhost iPad Air 4 - localhost

iPad Air 4 - localhost iPad Air 4 - localhost

iPhone 13 Pro - localhost iPhone 13 Pro - localhost iPhone 13 Pro - localhost

https://github.com/user-attachments/assets/b011a63b-9f03-47a4-a436-7866564a3113

### CODE REVIEW

**Comment by keshav-exe** [comment]
GREAT STUFF BRO!

**Comment by DeepanshuMishraa** [comment]
great work man!. Can you tell me how you made these different devices preview image?

**Comment by hkirat** [comment]
@devsargam

**Comment by devsargam** [comment]
Checking after few @hkirat

**Comment by Eshan-Sharma** [comment]
Thanks a lot, @devsargam closes issue #600

**Comment by Zafeeruddin** [comment]
Is this mege reverted
Cannot see it now 
image

**Pull request merged**
