### PR TITLE
Fix App Bar, Code Editor Theme

### PR DESCRIPTION
**Pull request by vcashwin**
## PR Fixes:
1. Fix theming and alignment issues for appbar buttons and code problem renderers

### Before:
image
image

### After:
image
image

2. Refactor code of BlogAppBar component to keep it clean.

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by nimit9** [comment]
Could you also fix theme issue for the problem page of type Code, I guess it also has issues with light theme

**Comment by vcashwin** [comment]
> Could you also fix theme issue for the problem page of type Code, I guess it also has issues with light theme

What is typeCode if I may ask? New to this repo :)

**Comment by vcashwin** [comment]
@nimit9 updated the PR with theme fixes for code editor. 

@hkirat quick review? :)

**Comment by nimit9** [comment]
The UI looks good to me!

**Comment by vcashwin** [comment]
Gentle bump for a review on this one @hkirat

**Comment by hkirat** [comment]
apologies I dropped the ball on this
Too many merge conflicts. Do u mind creating a new PR?

**Pull request closed without merging**
