### PR TITLE
Feat/responsive code block

### LINKED ISSUE #288: bug:code block overflows on mobile screens
On mobile screens, code blocks were overflowing beyond the screen width, making them unreadable.

https://github.com/code100x/daily-code/assets/81159771/e7439ad5-46af-423e-8ee3-a1dd222e93e4

### PR DESCRIPTION
**Pull request by prvn347**
- This pr fixes the codeblock overflowing issue.
- In this I have implemented CSS adjustments to ensure code blocks are properly contained within the viewport on mobile devices.
chrome-capture-2024-4-16

Resolves  #288

- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by hkirat** [comment]
Remove package lock

**Comment by prvn347** [comment]
removed package lock files
@hkirat  please check

**Comment by hkirat** [comment]
You also removed yarn.lock ser, please revert that

**Comment by ShubhamMewara** [comment]
@prvn347 
don't delete yarn.lock remove changes in the yarn.lock as the change you made doesn't require changes in yarn.lock file

**Comment by prvn347** [comment]
@hkirat sorry sir, please check now!

**Pull request closed without merging**
