### PR TITLE
feature: Added the ability to add the solution and let the users see their others' solutions

### LINKED ISSUE #484: feature: Implemented the feature of letting the user add their submissions of a problem and see others' solutions/submissions.
**Is your feature request related to a problem? Please describe.**
Its an extended functionality where user can submit their accepted submission and post them as a solutions and see others' solution.

**Solution**
The features integrates a markdown editor which lets the user add their approach.

### PR DESCRIPTION
**Pull request by ashish98joshi**
### PR Fixes:
Closes #484 

**Is your feature request related to a problem? Please describe.**
Its an extended functionality where user can submit their accepted submission and post them as a solutions and see others' solution.

**Solution**
The features integrates a markdown editor which lets the user add their approach.  

Here is the demo: https://www.loom.com/share/e2a24e8212bd469ca7ad0659b03a250b

**Things left to fix**
1. For some reason, the markdown isnt able to convert the heading (like converting ## Intuition to a heading). So, need to fix that.

### Checklist before requesting a review
- [X] I have performed a self-review of my code
- [X] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by ShubhamMewara** [comment]
@ashish98joshi 
We have a separate repo for this now https://github.com/code100x/algorithmic-arena

**Comment by ashish98joshi** [comment]
okay, got it.

**Comment by devsargam** [comment]
sorry, you know where to put up a pr 😄

**Comment by ashish98joshi** [comment]
@devsargam yeah, I completely forgot about closng this. Thanks for closing!

**Pull request closed without merging**
