### PR TITLE
Feat #14 : Enforced commitlint, prettier, eslint via Github Actions

### PR DESCRIPTION
**Pull request by ofcljaved**
# Pull Request Description
This pull request resolves issue #14 .

### Add github workflows
- YAML file check for conventional commit message then performs the linting and formating

### Remove lint-staged
- Not working precisely so remove it and changed the pre-commit hook

| Type     | Heading  | Rule                                       | Description                                                                                 |
| -------- | -------- | --------------------------------- | ------------------------------------------------------------------- |
| ci          | CI         | Continuous Integration            | Changes related to continuous integration.                               |
| chore    | Chore   | Maintenance tasks                          | Other changes that don't affect production.                      |
| docs     | Docs     | Documentation                              | Changes related to documentation.                                                 |
| feat     | Feature  | New Feature                                | New feature implementations or additions.                                         |
| fix      | Fix      | Bug Fixes                                  | Bug fixes or corrections.                                                         |
| perf     | Perf     | Performance Improvements                   | Performance-related improvements.                                                 |
| refactor | Refactor | Code Refactoring                           | Code changes that don't fix bugs or add features, but improve the code structure. |
| revert   | Revert   | Revert Previous Commits                    | Reverting previous commits.                                                       |
| style    | Style    | Code Formatting or Style                   | Changes related to code formatting or style.                                      |
| assets   | Assets   | Add or Update Assets (e.g., images, files) | Changes related to adding or updating assets, such as images or other files.      |

### CODE REVIEW

**Comment by ofcljaved** [comment]
@hkirat Can you look at this I don't get why I failed the checks But I have tried github actions on my test project and it enforces linting on PRs so can you review it

**Review by hkirat — CHANGES_REQUESTED** [review]
again keep it minimal, only have the esline and husky changes here

**Comment by ofcljaved** [comment]
Made it minimal and only had eslint through github actions or should I remove that too ??
@hkirat

**Comment by ofcljaved** [comment]
Now same as CMS pre-commit hook won't commit all the files after linting and it only checks for lint and format not going to fix it

**Comment by hkirat** [comment]
Some of these changes are already in (ref Blog Appbar)
Can u get rid of the conflicts?
Ideally just create 2 PRs
1. Adding the CI/CD pipeline
2. Updating husky pre commit hooks

**Comment by ofcljaved** [comment]
> Some of these changes are already in (ref Blog Appbar) Can u get rid of the conflicts? Ideally just create 2 PRs
> 
> 1. Adding the CI/CD pipeline
> 2. Updating husky pre commit hooks

Ohk I'll do it

**Comment by ofcljaved** [comment]
> * YAML file check for conventional commit message then performs the linting and formating



> Some of these changes are already in (ref Blog Appbar) Can u get rid of the conflicts? Ideally just create 2 PRs
> 
> 1. Adding the CI/CD pipeline
> 2. Updating husky pre commit hooks

Opened #325 for CI/CD
@hkirat

**Comment by ofcljaved** [comment]
> 2\. Updating husky pre commit hooks

Opened #326 for husky/pre-commit
@hkirat

**Pull request closed without merging**
