### PR TITLE
fixed the download-pdf option issue

### LINKED ISSUE #494: When using the Download option for a particular topic, generated PDF is NOT including the images and page break is not consistent
**Describe the bug**
When using the Download option for a particular topic, generated PDF is NOT including the images and page break is not consistent

**To Reproduce**
1. On the daily code website (https://projects.100xdevs.com/) select a topic by using the Explore option
2. Once the topic loads, select the Download option in the top right hand corner
3. Wait for the PDF to be generated
4. Once PDF is generated, we can see that the images are NOT present and pagination is incorrect

**Expected behavior**
Once PDF is generated, we MUST see that the images and pagination should be correct 
**Screenshots or GIFs**

**Info (please complete the following information):**
 - Browser Chrome 
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**

### PR DESCRIPTION
**Pull request by zenithexe**
### PR Fixes:
- 1 Makes the PDF page breaks consistent 
- 2 The Images in the generated PDF are well visible
- 3 The pagination bar in excluded in the generated pdf.

Resolves #494 

### Before Fix :
 - 1 Some of the images were getting hidden by the new blog-component
Bug1

- 2 The pagination was coming include in the pdf
Bug2

### After Fix :
- 1 The Page breaks were made consistent and Images were visible.
Fix1

- 2 The Pagination Component was excluded in the pdf
Fix2

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
cool

**Comment by zenithexe** [comment]
@devsargam by "reduce the diff", do you mean to eliminate the unnecessary changes that was caused due to useless line-shift or extra spaces ?

**Comment by devsargam** [comment]
Yep

**Comment by zenithexe** [comment]
@devsargam Since, I am new to open-source contributing, I am bit confused.
I have made the eliminated the unnecessary changes in my fork version and pushed it. So, we it be included in this pull request ?

**Comment by devsargam** [comment]
@zenithexe the reason why we try to eliminate unnecessary changes is just because I can get to what you did easily.

**Comment by zenithexe** [comment]
@devsargam Okk, I have already eliminated the unnecessary changes... and made a new commit. You can check.

**Comment by devsargam** [comment]
Works great locally. Thank you for your contribution. You will receive a bounty if it deserves one.

**Comment by skodavalla** [comment]
@devsargam no bounty for issue reporting? :-)

**Comment by devsargam** [comment]
@skodavalla issue reporting?

**Pull request merged**
