### PR TITLE
fix(ui): add a visual download PDF feature

### PR DESCRIPTION
**Pull request by devsargam**
Fixes: #55

This pr adds:
- [x] Functionality to download a notion file as pdf
- [x] Add a route at `/pdf/.../...` to convert notion doc to pdf
- [x] Add a visual button in AppBar component

My approach to this problem:
- Load all the notion slides in a single page
- Render the Appbar conditionally (don't render it on pdf)
- Use the native window.print function to convert the html into PDF
- Add a separate route under `pdf/.../...`

### CODE REVIEW

**Comment by devsargam** [comment]
@hkirat could you please review it?

**Comment by devsargam** [comment]
https://github.com/code100x/daily-code/assets/76874341/101480e4-ae0a-46cb-ace1-a862713d3aaf

**Comment by devsargam** [comment]
@hkirat ping for attention. could you please review this??

**Comment by thatbeautifuldream** [comment]
great work can you fix the file name as a the page title?

**Comment by hkirat** [comment]
Hi so sorry not getting the time to review
/bounty $120 
This loos great, will review later

**Comment by devsargam** [comment]
> great work can you fix the file name as a the page title?

Yea, sure thanks for the suggestion

**Comment by mumin-khan** [comment]
@devsargam Please ensure all content within toogle  buttons  is also printed in the pdf. 
I think you missed on it.
I have cloned your branch and it doesn't work.

P.S: Even when I opened the toggle buttons, the code opens a new page with all the toggle buttons closed. And pdf doesn't support text search as well.

**Comment by devsargam** [comment]
> @devsargam Please ensure all content within toogle  buttons  is also printed in the pdf. 
> I think you missed on it.
> I have cloned your branch and it doesn't work.
> 
> P.S: Even when I opened the toggle buttons, the code opens a new page with all the toggle buttons closed. And pdf doesn't support text search as well.

Alright I'll work on it right now thanks for the bug

**Comment by devsargam** [comment]
@mumin-khan please check. I've fixed the solution now showing up issue now.

**Comment by mumin-khan** [comment]
> @mumin-khan please check. I've fixed the solution now showing up issue now.

@devsargam It works now.
Saving the pdf as microsoft print to pdf creates a non searchable pdf while as simple save as pdf creates a searchable one.
Adding a hint to select save as pdf may be useful.
image

Also the track and pdf routes have almost the same code. It would be better to refactor the code to avoid duplication.

**Comment by devsargam** [comment]
> > @mumin-khan please check. I've fixed the solution now showing up issue now.
> 
> @devsargam It works now.
> Saving the pdf as microsoft print to pdf creates a non searchable pdf while as simple save as pdf creates a searchable one.
> Adding a hint to select save as pdf may be useful.
> image
> 
> Also the track and pdf routes have almost the same code. It would be better to refactor the code to avoid duplication.

> Haven't faced such issues actually maybe I'm on a mac
> And regarding the same code it's actually a little different so I don't think it requires a refactor

**Comment by mumin-khan** [comment]
> > > @mumin-khan please check. I've fixed the solution now showing up issue now.
> > 
> > 
> > @devsargam It works now.
> > Saving the pdf as microsoft print to pdf creates a non searchable pdf while as simple save as pdf creates a searchable one.
> > Adding a hint to select save as pdf may be useful.
> > image
> > Also the track and pdf routes have almost the same code. It would be better to refactor the code to avoid duplication.
> 
> * Haven't faced such issues actually maybe because I'm on a mac
> * And regarding the same code it's actually a little different so I don't think it requires a refactor

I would respectfully disagree with the your opinion here.

I think you are passing the same problemDetail for all pages in a track.

**Comment by hkirat** [comment]
@devsargam can u fix the merge conflicts

**Comment by hkirat** [comment]
merged in a few PRs, might've broken something

**Comment by devsargam** [comment]
or did u change something related to firebase or notion?

**Comment by devsargam** [comment]
Also, you can merge this @hkirat

**Comment by AdiGaikwad** [comment]
Hey @devsargam 
Can you check if it is working on https://projects.100xdevs.com/ ?
As it is giving me a blank page as pdf

**Comment by devsargam** [comment]
@AdiGaikwad yeppp, seems something is wrong I'm investigating

**Comment by devsargam** [comment]
But it does give correct for few cases right?

**Comment by AdiGaikwad** [comment]
> @AdiGaikwad yeppp, seems something is wrong I'm investigating

I checked for 2 tracks both of them gave a blank page 
I will check more

**Comment by thrishank** [comment]
Hey, @devsargam  the solutions are not opening on the website. It's working locally but in the production, it doesn't
image

**Comment by devsargam** [comment]
There is a pr which hopefully fixes that @thrishank

**Pull request merged**
