### PR TITLE
fix: note download bug

### PR DESCRIPTION
**Pull request by mumin-khan**
### PR Fixes:
Fixes the download note bug

Other prs have proposed a different libraray for this.
Resolves [#334] 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by mumin-khan** [comment]
fixes #334

**Comment by SujithThirumalaisamy** [comment]
There is already a PR reg this IG. Please check before raising one

**Comment by mumin-khan** [comment]
@SujithThirumalaisamy I know but doesn't address the bug as I have said. It introduces a new Library altogether.

**Comment by mumin-khan** [comment]
@hkirat I think the bugs exists in daily-code as well.

**Pull request closed without merging**
