### PR TITLE
added db calls from postgres in nextjs app

### LINKED ISSUE #113: Migrating to postgres
I feel like this'll just get harder and harder as time goes by

We don't have dependency on auth right now so the best time to move off of it

Let's migrate over to postgres + prisma and get rid of firebase completely

This is the schema of the DB right now - 

Tracks
Screenshot 2024-04-02 at 8 39 49 PM

Problems
Screenshot 2024-04-02 at 8 39 59 PM

So the final DB should be like this - 
Tracks
title
description
image
visible: boolean

Problems
title
description
type: "blog" | "code"

track_problems
id
problem_id
track_id
sort_order

### PR DESCRIPTION
**Pull request by nimit9**
Fixes #113 

- added backend endpoints to nextjs so we can get rid of all the firebase calls

@hkirat haven't changes to admin part, will do that when integrating auth.

### CODE REVIEW

**Comment by hkirat** [comment]
/bounty $75
No need to update admin part remove it infact no one uses it right now

**Comment by nimit9** [comment]
> /bounty $75
> No need to update admin part remove it infact no one uses it right now
> 

Okay, sure!

**Comment by hkirat** [comment]
LMK if u need access to firebase

**Comment by nimit9** [comment]
Only have to perform reads, will be able to do that. Won't be needed most prolly

**Pull request merged**
