### PR TITLE
Fix: Scrollbar is not visible in light mode

### PR DESCRIPTION
**Pull request by karananeja**
### PR Fixes:
- 1 Scroll bar color is updated for light mode to make it more visible

Resolves #[Issue Number if there] #240 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by vishalmishraa** [comment]
there is lot of unwanted new lines , you can remove that , and try this code  , : 
just replace these 

```
/* Scroll Bar */
::-webkit-scrollbar {
	width: 10px;
}

::-webkit-scrollbar-thumb {
  background-color: rgb(0, 0, 0);
  border-radius: 8px;
}

```

**Comment by hkirat** [comment]
Too much noise in the PR

**Comment by karananeja** [comment]
@vishalmishraa
1. I've refactored the code, and we'll need the height property for the scrollbar if the scrollbar occurs in horizontal direction
2. The new lines are due to formatting the file, it actually had a space on each line which is formatted automatically to remove that space on each line

**Comment by iamgauravbisht** [comment]
> @vishalmishraa
> 1. I've refactored the code, and we'll need the height property for the scrollbar if the scrollbar occurs in horizontal direction
> 2. The new lines are due to formatting the file, it actually had a space on each line which is formatted automatically to remove that space on each line
> 
> @hkirat 
> Didn't understand, what do you mean by noise?

Remove comments from the code

**Comment by mumin-khan** [comment]
@karananeja this also been fixed i guess.

**Comment by karananeja** [comment]
@mumin-khan I think it's not fixed yet.

**Pull request closed without merging**
