### PR TITLE
Refactor Print component to use useRouter hook and add delay before printing

### PR DESCRIPTION
**Pull request by impruthvi**
In the local environment, the print function is not working; it directly redirects to the main screen, and the print page is blank. Therefore, I added a delay, and after printing, I closed the current tab.

### CODE REVIEW

**Comment by devsargam** [comment]
bhai but don't you think this could introduce some other problems? Like what if pdf took more than 1s to load?

**Comment by impruthvi** [comment]
> bhai but don't you think this could introduce some other problems? Like what if pdf took more than 1s to load?

Yes, you are right for that. Now, I added an afterprint listener.

**Comment by hkirat** [comment]
Sorry seems like there are merge conflicts

**Comment by impruthvi** [comment]
@hkirat resolved conflict

**Comment by hkirat** [comment]
.bounty $5

**Pull request merged**
