### PR TITLE
added section for Cohort 3

### PR DESCRIPTION
**Pull request by ShubhamMewara**
### PR Fixes: #504 

- [x] Added filter button for cohort 3
- [x] add option to edit(add or delete) category

https://github.com/user-attachments/assets/4003b439-284e-47fc-97d7-80da71eda291

### CODE REVIEW

**Comment by TanmayDhobale** [comment]
@ShubhamMewara Great!

**Comment by devsargam** [comment]
@ShubhamMewara can u get rid of conflicts?
Also, is this backward compatible with the current database schema?

**Comment by ShubhamMewara** [comment]
@devsargam Yes default `cohort` is 0 if the track is not related to Cohort 3 then it will not show in the Cohort 3 section

**Comment by devsargam** [comment]
Cool, Thanks.

**Pull request merged**
