### PR TITLE
feat : Added the Leetcode like heatmap feature for user's submissions

### LINKED ISSUE #410: feature: Implemented the Leetcode like heatmap feature for user's submissions
### **Problem Statement**

Currently, in the daily-code project, users can submit their code solutions similar to the LeetCode platform, and they can view their accepted submissions in their profiles. However, there is a lack of functionality for users to effectively track their accountability and progress over time. This limitation diminishes the user experience and prevents users from setting and achieving goals related to their daily coding practice and along with that if I am not wrong , Harkirart has also mentioned in one of his recent video that he is supposed to build leetcode like features end-to-end.

### **Solution** :
To solve this issue , I have implemented a heatmap feature inspired by platform like LeetCode. This feature provides users with a visual representation of their coding activity over time, allowing them to track their progress, identify patterns, and stay motivated in their coding journey. 
In this version of Heatmap , Users can not only see the entire year once but also can individually see each month according to them .

Below is how the changes looks like : 
image
 
On hovering date box
image

**In action :** 

https://github.com/code100x/daily-code/assets/118182376/b144b366-7a23-41ee-a53b-8d5c32ae8cc5

### PR DESCRIPTION
**Pull request by amanbairagi30**
### **Problem Statement**

Currently, in the daily-code project, users can submit their code solutions similar to the LeetCode platform, and they can view their accepted submissions in their profiles. However, there is a lack of functionality for users to effectively track their accountability and progress over time. This limitation diminishes the user experience and prevents users from setting and achieving goals related to their daily coding practice and along with that if I am not wrong , Harkirart has also mentioned in one of his recent video that he is supposed to build leetcode like features end-to-end.

### **Solution :**

To solve this issue , I have implemented a heatmap feature inspired by platform like LeetCode. This feature provides users with a visual representation of their coding activity over time, allowing them to track their progress, identify patterns, and stay motivated in their coding journey.
In this version of Heatmap , Users can not only see the entire year once but also can individually see each month according to them .

Below is how the changes looks like :
image

On hovering date box

image

In action : 

https://github.com/code100x/daily-code/assets/118182376/c117e043-a375-4669-aac8-1734fda2f4be

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by amanbairagi30** [comment]
Hello @hkirat , Please review this PR

**Comment by hkirat** [comment]
yes sir
great one
Will do a review stream today mostly

**Comment by amanbairagi30** [comment]
> yes sir
> great one
> Will do a review stream today mostly

Okay sir , sounds good 👍

**Comment by devsargam** [comment]
This is outdated for this repo we are not thinking of doing this here
Check the algo-arena repo and add a pr there

**Comment by amanbairagi89** [comment]
> This is outdated for this repo we are not thinking of doing this here
> Check the algo-arena repo and add a pr there

Okay sure

**Comment by amanbairagi30** [comment]
> This is outdated for this repo we are not thinking of doing this here
> Check the algo-arena repo and add a pr there

Okay sure

**Pull request closed without merging**
