### PR TITLE
Feat search

### PR DESCRIPTION
**Pull request by ShubhamMewara**
### PR Fixes: #175 

used algolia for search

https://github.com/code100x/daily-code/assets/136337515/4dd91f39-197b-4b58-89cd-11b98dd5e087

### CODE REVIEW

**Comment by ShubhamMewara** [comment]
hey @hkirat can you please review this

**Comment by ShubhamMewara** [comment]
@hkirat 
https://www.algolia.com/pricing/
it's is free up to 10k search requests / month and
$0.50 per additional 1k search requests

**Comment by ShubhamMewara** [comment]
@hkirat 
Another example 

https://github.com/code100x/daily-code/assets/136337515/8001d495-ab2c-4204-bf63-0f304b62ff56

**Comment by mumin-khan** [comment]
@ShubhamMewara great work.
The only thing which I feel you can improve is filter duplicate track ids which are shown on search.

**Comment by ShubhamMewara** [comment]
> @ShubhamMewara great work. The only thing which I feel you can improve is filter duplicate track ids which are shown on search.

Search returns Problems not tracks so it's not duplicate Tracks but different problems of the same track

**Pull request closed without merging**
