### PR TITLE
added-fuse.js

### LINKED ISSUE #556: bug: Searching functionality is not working properly
Screenshot (330)

Searching functionality is not actually working. I have typed lots but not responding.

### LINKED ISSUE #576: feature: add a search on the frontend
**Is your feature request related to a problem? Please describe.**
Currently, the search functionality is not working properly since the API key for search has expired.

**Describe the solution you'd like**
Just search the title of all the topics we are getting from the backend. Use [Fuse.js](https://www.fusejs.io/) to do some fuzzy search.

**Additional context**
Don't remove the elastic search logic just replace with fusejs as an interim solution

### PR DESCRIPTION
**Pull request by Ashutoshpadhi629**
### PR Fixes:
- 1 added fuse.js for search-bar

Resolves #576 

https://github.com/user-attachments/assets/dc8c57ed-41ba-4b46-bc99-16accd38a145

 

### Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I assure there is no similar/duplicate pull request regarding same issue

### CODE REVIEW

**Comment by Ashutoshpadhi629** [comment]
hey @devsargam , applied fuse.js for client side search , also didn't delete any of the previous logic , bought the tracks from the parent obj to the searchBar , made a variable similar to previous obj 
`updatedTracks.push({
          payload: {
            problemId: p.id,
            trackTitle: t.title,
            problemTitle: p.title,
            trackId: t.id,
            image: t.image,
          },`
    so that most of the previous logic is still there , can you review this please.

**Comment by devsargam** [comment]
Testing it

**Comment by devsargam** [comment]
@Ashutoshpadhi629 
image

Search works but the design doesn't look good

**Comment by devsargam** [comment]
@Ashutoshpadhi629 thank u sir.

**Comment by Ashutoshpadhi629** [comment]
> @Ashutoshpadhi629 thank u sir.

@devsargam thank you for the review sir

**Pull request merged**
